base_path: .
export_languages:
  - et
  - fi
  - fr
  - ru
  - id
files:
  -
    source: /src/**/*.en.yaml
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    translation_replace:
      en.: ''
  -
    source: /subtitles/*.en.srt
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    translation_replace:
      en.: ''
